### PR TITLE
[melodic-devel][18.04] fix compile errors

### PR DESCRIPTION
**Pull request by moriarty**
fix compile errors for newer gcc

### CODE REVIEW

**Comment by moriarty** [comment]
@mikeferguson could you open a melodic-devel branch?

I'll submit PRs to open_karto & slam_karto for melodic soon too.

**Comment by mikeferguson** [comment]
Branch created -- this PR retargeted

**Comment by moriarty** [comment]
Bump @rctoris & @mikeferguson

**Comment by mikeferguson** [comment]
Release created: https://github.com/ros/rosdistro/pull/18884

**Comment by moriarty** [comment]
Thanks, @stfuchs and I have two more commits from today which I'll open an new PR for

**Pull request merged**
